# Generated by Django 5.2.7 on 2025-10-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=250, null=True)),
                ('model_year', models.IntegerField(null=True)),
                ('Travelled_dist', models.IntegerField(null=True)),
                ('first_owner', models.BooleanField(null=True)),
                ('second_owner', models.BooleanField(null=True)),
                ('front_image1', models.ImageField(null=True, upload_to='images/front/')),
                ('front_image2', models.ImageField(null=True, upload_to='images/front/')),
                ('front_image3', models.ImageField(null=True, upload_to='images/front/')),
                ('front_image4', models.ImageField(null=True, upload_to='images/front/')),
                ('front_image5', models.ImageField(null=True, upload_to='images/front/')),
                ('picture1', models.ImageField(null=True, upload_to='images/main/')),
                ('picture2', models.ImageField(null=True, upload_to='images/main/')),
                ('picture3', models.ImageField(null=True, upload_to='images/main/')),
                ('picture4', models.ImageField(null=True, upload_to='images/main/')),
                ('picture5', models.ImageField(null=True, upload_to='images/main/')),
            ],
        ),
    ]
