# Generated by Django 5.2.7 on 2025-10-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='front_image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/front/'),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='front_image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/front/'),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='front_image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/front/'),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='front_image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/front/'),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='front_image5',
            field=models.ImageField(blank=True, null=True, upload_to='images/front/'),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='images/main/'),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='images/main/'),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='images/main/'),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='images/main/'),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='picture5',
            field=models.ImageField(blank=True, null=True, upload_to='images/main/'),
        ),
    ]
