# Generated by Django 5.2.7 on 2025-10-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardetails', '0002_alter_cardetails_front_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetails',
            name='Travelled_dist',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='car_name',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='first_owner',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='front_image1',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='front_image2',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='front_image3',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='front_image4',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='front_image5',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='model_year',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='second_owner',
        ),
        migrations.AddField(
            model_name='cardetails',
            name='color',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='description',
            field=models.TextField(default='Vehicle descriptions here'),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='fuel_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='gear',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='insurance',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='model',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='owner',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='picture10',
            field=models.ImageField(blank=True, null=True, upload_to='images/main/'),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='picture11',
            field=models.ImageField(blank=True, null=True, upload_to='images/main/'),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='picture12',
            field=models.ImageField(blank=True, null=True, upload_to='images/main/'),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='picture13',
            field=models.ImageField(blank=True, null=True, upload_to='images/main/'),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='picture14',
            field=models.ImageField(blank=True, null=True, upload_to='images/main/'),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='picture15',
            field=models.ImageField(blank=True, null=True, upload_to='images/main/'),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='picture6',
            field=models.ImageField(blank=True, null=True, upload_to='images/main/'),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='picture7',
            field=models.ImageField(blank=True, null=True, upload_to='images/main/'),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='picture8',
            field=models.ImageField(blank=True, null=True, upload_to='images/main/'),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='picture9',
            field=models.ImageField(blank=True, null=True, upload_to='images/main/'),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='seats',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='vehicle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
