# Generated by Django 5.2.7 on 2025-10-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardetails', '0003_remove_cardetails_travelled_dist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='model',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
