# Generated by Django 5.2.7 on 2025-10-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardetails', '0004_alter_cardetails_fuel_type_alter_cardetails_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phn_no', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
