# Generated by Django 5.2.7 on 2025-10-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardetails', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phn_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
